
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GmailImplService", targetNamespace = "http://appServidor/", wsdlLocation = "http://localhost:8080/WS/Gmail/V1.0?wsdl")
public class GmailImplService
    extends Service
{

    private final static URL GMAILIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException GMAILIMPLSERVICE_EXCEPTION;
    private final static QName GMAILIMPLSERVICE_QNAME = new QName("http://appServidor/", "GmailImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Gmail/V1.0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GMAILIMPLSERVICE_WSDL_LOCATION = url;
        GMAILIMPLSERVICE_EXCEPTION = e;
    }

    public GmailImplService() {
        super(__getWsdlLocation(), GMAILIMPLSERVICE_QNAME);
    }

    public GmailImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GMAILIMPLSERVICE_QNAME, features);
    }

    public GmailImplService(URL wsdlLocation) {
        super(wsdlLocation, GMAILIMPLSERVICE_QNAME);
    }

    public GmailImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GMAILIMPLSERVICE_QNAME, features);
    }

    public GmailImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GmailImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GmailInterface
     */
    @WebEndpoint(name = "GmailImplPort")
    public GmailInterface getGmailImplPort() {
        return super.getPort(new QName("http://appServidor/", "GmailImplPort"), GmailInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GmailInterface
     */
    @WebEndpoint(name = "GmailImplPort")
    public GmailInterface getGmailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://appServidor/", "GmailImplPort"), GmailInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GMAILIMPLSERVICE_EXCEPTION!= null) {
            throw GMAILIMPLSERVICE_EXCEPTION;
        }
        return GMAILIMPLSERVICE_WSDL_LOCATION;
    }

}
